// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: g4Ez5Lq65bFwpS9M8VgRuA
// Component: Vwv2WO9OUy34Z
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: RYN9c2WQmTlJA/component
import ProductGrid from "../../ProductGrid"; // plasmic-import: 2H8_-Jd25igKZ/component
import { ProductBox } from "@plasmicpkgs/commerce"; // plasmic-import: 1gYJf_XBZUAD/codeComponent
import ProductCard from "../../ProductCard"; // plasmic-import: FvHW5jBcyeTo6/component
import { ProductTextField } from "@plasmicpkgs/commerce"; // plasmic-import: S1F4q0wN6b/codeComponent
import ReactFastMarquee from "../../code-components/ReactFastMarquee"; // plasmic-import: GPE0NlN9XsWg-/codeComponent
import Hero from "../../Hero"; // plasmic-import: bMAhaNV4uxtZt/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_plasmic_kit_q_4_color_tokens_css from "../plasmic_kit_q_4_color_tokens/plasmic_plasmic_kit_q_4_color_tokens.module.css"; // plasmic-import: 95xp9cYcv7HrNWpFWWhbcv/projectcss
import projectcss from "./plasmic_next_js_commerce.module.css"; // plasmic-import: g4Ez5Lq65bFwpS9M8VgRuA/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: Vwv2WO9OUy34Z/css

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  marquee?: p.Flex<"div">;
  marquee2?: p.Flex<"div">;
};

export interface DefaultHomepageProps {}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_plasmic_kit_q_4_color_tokens_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <ProductGrid
            className={classNames("__wab_instance", sty.productGrid___8Z1E)}
            product0={
              <ProductBox
                className={classNames("__wab_instance", sty.productBox__ytzBo)}
                id={"gid://shopify/Product/5447322697892" as const}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__mNaU
                  )}
                  color={"violet" as const}
                />
              </ProductBox>
            }
            product1={
              <ProductBox
                className={classNames("__wab_instance", sty.productBox__apHt)}
                id={"gid://shopify/Product/5447323156644" as const}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ntX02
                  )}
                  color={"white" as const}
                />
              </ProductBox>
            }
            product2={
              <ProductBox
                className={classNames("__wab_instance", sty.productBox__pxd4N)}
                id={"gid://shopify/Product/5447323812004" as const}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__tGgh
                  )}
                  color={"pink" as const}
                />
              </ProductBox>
            }
          />

          <div
            data-plasmic-name={"marquee"}
            data-plasmic-override={overrides.marquee}
            className={classNames(projectcss.all, sty.marquee)}
          >
            {true ? (
              <ReactFastMarquee
                className={classNames(
                  "__wab_instance",
                  sty.reactFastMarquee__olm2V
                )}
                gradient={false}
              >
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox___5OAuD)}
                    test={"test" as const}
                  >
                    <ProductBox
                      className={classNames(
                        "__wab_instance",
                        sty.productBox__bKxwe
                      )}
                      id={"gid://shopify/Product/5447322697892" as const}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__voEnl
                        )}
                        shape={"slim" as const}
                      />
                    </ProductBox>
                  </div>
                ) : null}
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox___1XLtg)}
                  >
                    <ProductBox
                      className={classNames(
                        "__wab_instance",
                        sty.productBox__gUigv
                      )}
                      id={"gid://shopify/Product/5447323156644" as const}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__v85RJ
                        )}
                        shape={"slim" as const}
                      />
                    </ProductBox>
                  </div>
                ) : null}
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__irVj)}
                  >
                    <ProductBox
                      className={classNames(
                        "__wab_instance",
                        sty.productBox__yzwwf
                      )}
                      id={"gid://shopify/Product/5447323812004" as const}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__l3ZyN
                        )}
                        shape={"slim" as const}
                      />
                    </ProductBox>
                  </div>
                ) : null}
              </ReactFastMarquee>
            ) : null}
          </div>

          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__e91Ou)}>
              <Hero className={classNames("__wab_instance", sty.hero__ptGpB)} />
            </div>
          ) : null}

          <ProductGrid
            className={classNames("__wab_instance", sty.productGrid__pzard)}
            layout={"b" as const}
            product0={
              <ProductBox
                className={classNames("__wab_instance", sty.productBox__aUq98)}
                id={"gid://shopify/Product/5447322697892" as const}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__dljv
                  )}
                  color={"violet" as const}
                />
              </ProductBox>
            }
            product1={
              <ProductBox
                className={classNames("__wab_instance", sty.productBox__v9UD1)}
                id={"gid://shopify/Product/5447323156644" as const}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__cc9Je
                  )}
                  color={"white" as const}
                />
              </ProductBox>
            }
            product2={
              <ProductBox
                className={classNames("__wab_instance", sty.productBox__xSjtV)}
                id={"gid://shopify/Product/5447323812004" as const}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__odrGe
                  )}
                  color={"pink" as const}
                />
              </ProductBox>
            }
          />

          <div
            data-plasmic-name={"marquee2"}
            data-plasmic-override={overrides.marquee2}
            className={classNames(projectcss.all, sty.marquee2)}
          >
            {true ? (
              <ReactFastMarquee
                className={classNames(
                  "__wab_instance",
                  sty.reactFastMarquee___3PXDx
                )}
                gradient={false}
              >
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bWcxb)}
                    test={"test" as const}
                  >
                    <ProductBox
                      className={classNames(
                        "__wab_instance",
                        sty.productBox__vKFq
                      )}
                      id={"gid://shopify/Product/5447324270756" as const}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard___9UtKn
                        )}
                        color={"black" as const}
                        shape={"slim" as const}
                      />
                    </ProductBox>
                  </div>
                ) : null}
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox___1XLtg)}
                  >
                    <ProductBox
                      className={classNames(
                        "__wab_instance",
                        sty.productBox__nMpU4
                      )}
                      id={"gid://shopify/Product/5447324729508" as const}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__d1QW
                        )}
                        color={"black" as const}
                        shape={"slim" as const}
                      />
                    </ProductBox>
                  </div>
                ) : null}
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__irVj)}
                  >
                    <ProductBox
                      className={classNames(
                        "__wab_instance",
                        sty.productBox__duASx
                      )}
                      id={"gid://shopify/Product/5447325024420" as const}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__dkzOz
                        )}
                        color={"black" as const}
                        shape={"slim" as const}
                      />
                    </ProductBox>
                  </div>
                ) : null}
              </ReactFastMarquee>
            ) : null}
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navbar", "marquee", "marquee2"],
  navbar: ["navbar"],
  marquee: ["marquee"],
  marquee2: ["marquee2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  marquee: "div";
  marquee2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    marquee: makeNodeComponent("marquee"),
    marquee2: makeNodeComponent("marquee2"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
