// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { useRouter } from "next/router";
import * as React from "react";
import GlobalContextsProvider from "../../components/plasmic/next_js_commerce/PlasmicGlobalContextsProvider";

import { PlasmicProduct } from "../../components/plasmic/next_js_commerce/PlasmicProduct";

function Product() {
  // Use PlasmicProduct to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicProduct are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.

  const router = useRouter();
  const id = router.query.slug ? router.query.slug[0] : undefined;
  
  return (
    <GlobalContextsProvider>
      <PlasmicProduct
        productBox={{id}}
        productFetch={{id}}
      />
    </GlobalContextsProvider>
  );
}

export default Product;
