// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { useRouter } from "next/router";
import * as React from "react";
import GlobalContextsProvider from "../../components/plasmic/next_js_commerce/PlasmicGlobalContextsProvider";

import { PlasmicSearch } from "../../components/plasmic/next_js_commerce/PlasmicSearch";
import { useCategories } from "@plasmicpkgs/commerce";

function Search() {
  // Use PlasmicSearch to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicSearch are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.

  const router = useRouter();

  const categoryId = router.query.slug ? router.query.slug[0] : undefined;

  const { data: category } = useCategories({categoryId});

  return (
    <GlobalContextsProvider>
      <PlasmicSearch
        productCollection={{
          category: categoryId && category ? category[0].id : undefined,
          sort: router.query.sort as string | undefined,
          search: router.query.query as string | undefined,
        }}
      />
    </GlobalContextsProvider>
  );
}

export default Search;
